### PR TITLE
OCaml 5.0.0

### PR DESCRIPTION
**Pull request by monadius**
This pull request updates OCaml to the latest version 5.0.0. Major changes from the previous version:

1) Solution, preloaded and test files are not concatenated. Three separate files are required to run tests: `solution.ml`, `tests.ml`, `preloaded.ml` (`preloaded.ml` is optional if other modules do not import it). It is now necessary to import all modules explicitly. It is possible to preprocess old tests to update most katas automatically: If an existing test file starts with the line `module Tests = struct`, then it is enough to delete this line and the last line (something like `end` or `end;;`) and insert
   ```ocaml
   open Solution
   open Preloaded
   ```
   at the very beginning of `tests.ml`. It may also be necessary to insert `open Preloaded` to the solution file if `preloaded.ml` is not empty.

2) `Core` is replaced with `Base` which is a lightweight version of `Core`.

3) `Num` is replaced with `Zarith` (a recommended OCaml package for arbitrary precision arithmetic). `Num` is still installed as a dependency of `Batteries` so old katas which rely on `Num` should still work.

4) A new package `Domainslib` is added to simplify parallel programming in OCaml 5.0.0 (the main feature of this major version of OCaml).

The updated OCaml version uses `ocamlbuild` to compile the project. It works well for simple projects with a few files. Later, we may replace `ocamlbuild` with `dune` (the modern OCaml build system) if any issues with `ocamlbuild` are discovered.

I also experimented with Alpine 3.17 (image size 565MB) and Ubuntu 22.04 (image size 645MB) images. The default image uses Alpine 3.17. But I observed that it may be slower than Ubuntu when arbitrary precision arithmetic is used in OCaml (see `examples/zarith`): 14.6 seconds vs 8.6 seconds for Ubuntu. I tested several existing katas which use `Num` and I did not observe any significant performance differences. So I think it is fine to use the Alpine image for now.

### CODE REVIEW

**Review by kazk — COMMENTED** [review]
Looks good to me overall.

Can you add `.github/workflows/ci.yml` like https://github.com/codewars/haskell/blob/main/.github/workflows/ci.yml to build the image and run some examples?

> I also experimented with Alpine 3.17 (image size 565MB) and Ubuntu 22.04 (image size 645MB) images. The default image uses Alpine 3.17. But I observed that it may be slower than Ubuntu when arbitrary precision arithmetic is used in OCaml (see `examples/zarith`): 14.6 seconds vs 8.6 seconds for Ubuntu. I tested several existing katas which use `Num` and I did not observe any significant performance differences. So I think it is fine to use the Alpine image for now.

Is there a reason to use Alpine other than the size? It seems safer to use Ubuntu, and the size difference is negligible.

**Comment by monadius** [comment]
I am traveling right now. I'll return home on Monday and then I will add the requested git workflow file.

I chose Alpine because both Coq and Agda images use it. I agree that it is safer to use Ubuntu since it does not demonstrate any performance issues for big integers. I will change the default image to Ubuntu.

**Comment by monadius** [comment]
I added `.github/workflows/ci.yml`. I also changed the default image to Ubuntu.

**Review by kazk — APPROVED** [review]

**Comment by kazk** [comment]
Thanks! I'll merge this tomorrow.

**Pull request merged**
